#data
dataset_args:
  mat_path: data/WebKB_cornell.mat                   #
  topk: 10
  train_ratio: 0.1

#model
model_class_args:
  module_path: models.model
  class_name: ASGCN
model_args:                         #
  n_layer: 5
  hid_dim: 56
  alpha: 0.1 #h0
  lamda: 0.5


optimizer_class_args:
  module_path: torch.optim
  class_name: Adam
optimizer_args:
  lr: 0.001
scheduler_class_args:
  module_path: torch.optim.lr_scheduler
  class_name: ReduceLROnPlateau
scheduler_args:
  mode: min
  factor: 0.3
  patience: 10
  min_lr: 1.0e-8
  verbose: False
scheduler_monitor: val_loss



#training
seed: 769
device: cuda
epochs: 1500
quiet: False
earlystop_args:
  checkpoint_dir: ./checkpoint/WebKB_cornell
  monitor: val_metric_acc
  patience: 100
  restore_best_weights: True
  save_best_only: True